language: go

go:
  - 1.x

services:
  - redis-server
env:
  - REDISURL=127.0.0.1:6379

before_script:
  - cd tests

script:
  - go get -d -t -v ./...
  - go test resq_test.go job_test.go
  - go test resq_test.go worker_test.go
  - go test scheduler_test.go
