language: go

go:
  - 1.x

services:
  - redis-server
env:
  - REDISURL=127.0.0.1:6379

before_script:
  - cd tests

script:
  - go test resq.go config.go job.go stat.go worker.go dispatcher.go constants.go resq_test.go job_test.go worker_test.go
  - go test resq.go config.go job.go stat.go worker.go dispatcher.go constants.go scheduler.go scheduler_test.go
