language: go

go:
  - 1.x

services:
  - redis-server
env:
  - REDISURL=127.0.0.1:6379
  - REDIS_PW=mypassword

before_script:
  - cd gores

script:
  - go test gores.go config.go job.go stat.go worker.go dispatcher.go constants.go gores_test.go job_test.go worker_test.go
  - go test gores.go config.go job.go stat.go worker.go dispatcher.go constants.go scheduler.go scheduler_test.go
